# items.py
# A dictionary of the items for each feature code

items = {'aircrft_flty':	['name',
                         	'facility',
                         	'q_info',
                         	'symbol',
                         	'feat_wid',
                         	'orientation',
                         	'old_ufi'],

'builtup_a':			['name',
                      		'q_info',
                      		'ufi',
                      		'symbol',
                      		'old_ufi'],

'bua_void':			['q_info',
                     		'ufi',
                     		'symbol',
                     		'old_ufi'],

'park':				['name',
                                 'park',
                                 'q_info',
                                 'ufi',
                                 'symbol',
                                 'text_note'],

'cemetery':			['name',
                                 'q_info',
                                 'ufi',
                                 'symbol',
                                 'text_note'],

'builtup_l':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'tile_edge':			['q_info',
				'ufi',
				'symbol'],

'hypso_a':			['elevation',
				'q_info',
				'ufi',
				'symbol'],

'contour':			['elevation',
				'contour',
				'q_info',
				'symbol'],

'canal':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'connector':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'watercours_l':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'rapid_l':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'spillway':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'fall_p':			['name',
				'q_info',
				'ufi',
				'symbol',
				'orentation',
				'feat_wid',
				'text_note'],

'lock':				['name',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'waterhole':			['name',
				'perennial',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'oorientation',
				'text_note'],

'spot_elevatn':			['elevation',
				'source',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'oreintation',
				'old_ufi'],

'island':			['name',
				'state',
				'q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'sea':				['name',
				'q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'mainland':			['state',
				'q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'junction':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'state_border':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'sea_wall':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'waterline':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'building':			['building',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'breakwater':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'wharf':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'jetty':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'boat_ramp':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'building_a':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'building_l':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'windbreak':			['q_info',
				'ufi',
				'symbol'],

'powerline':			['q_info',
				'ufi',
				'symbol'],

'locality':			['name',
				'locality',
				'q_info',
				'ufi',
				'symbol',
				'feat_width',
				'orientation',
				'text_note',
				'old_ufi'],

'cliff':			['q_info',
				'ufi',
				'text_note'],

'levee':			['q_info',
				'ufi',
				'symbol'],

'cutting':			['q_info',
				'ufi',
				'symbol'],

'embankment':			['q_info',
				'ufi',
				'symbol'],

'pinnacle':			['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'cave':				['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'lighthouse':			['name',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'wreck':			['name',
				'relationship',
				'q_info',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'rock_offshor':			['name',
				'relationship',
				'q_info',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'forshor_flat':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'offshor_flat':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'reef':				['name',
				'relationship',
				'reef',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'offshor_l':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'pipeline':			['product',
				'relationship',
				'reef',
				'q_info',
				'name',
				'symbol',
				'text_note'],

'rocky_a':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'dist_surf':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'sand':				['q_info',
				'ufi',
				'symbol'],

'crater':			['q_info',
				'ufi',
				'name',
				'symbol',
				'text_note'],

'open_cut':			['q_info',
				'ufi',
				'name',
				'symbol',
				'text_note'],

'dunes':			['q_info',
				'ufi',
				'symbol'],

'rel_a_void':			['q_info',
				'ufi',
				'symbol'],

'rel_area_l':			['q_info',
				'ufi',
				'symbol'],

'railway':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'bridge_rl_l':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'text_note',
				'old_ufi'],

'tunnel_rl_l':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'causeway_rl':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'text_note'],

'bridge_rl_p':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'old_ufi'],

'tunnel_rl_p':			['name',
				'status',
				'tracks',
				'gauge',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'old_ufi'],

'rail_station':			['name',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'old_ufi'],

'sand_ridge':			['average_height',
				'q_info',
				'ufi',
				'symbol'],

'forest':			['q_info',
				'ufi',
				'symbol'],

'rainforest':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'pine':				['q_info',
				'ufi',
				'symbol',
				'text_note'],

'orchard':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'mangrove':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'veg_void':			['q_info',
				'ufi',
				'symbol'],

'veg_l':			['q_info',
				'ufi',
				'symbol'],

'fence':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'dam':				['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'chairlift':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'conveyor':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'gas_well':			['q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'stor_tank_p':			['q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'yard':				['q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'mine':				['name',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'landmark_p':			['description',
				'q_info',
				'height',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'road':				['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'text_note',
				'old_ufi'],

'bridge_rd_l':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'text_note',
				'old_ufi'],

'tunnel_rd_l':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'ferry_route':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'foot_track':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'foot_bridge':			['name',
				'q_info',
				'ufi',
				'symbol'],

'causeway_rd':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info_ufi',
				'symbol',
				'feat_wid',
				'text_note'],

'road_on_dam':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'text_note'],

'ford_l':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'bridge_rd_p':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'old_ufi'],

'tunnel_rd_p':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'old_ufi'],

'gate':				['q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'grid':				['q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation'],

'ford_p':			['name',
				'class',
				'formation',
				'nrn',
				'srn',
				'q_info',
				'ufi',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'lake':				['name',
				'perennial',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'sub_to_inund':			['name',
				'q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'mangrove_flt':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'reservoir':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'saln_cst_flt':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'swamp':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'watercours_a':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'text_note',
				'old_ufi'],

'w_body_void':			['q_info',
				'ufi',
				'symbol',
				'old_ufi'],

'rapid_a':			['name',
				'perennial',
				'hierarchy',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'swamp_marine':			['q_info',
				'ufi',
				'symbol',
				'text_note'],

'salt_evapor':			['q_info',
				'ufi',
				'symbol',
				'text_note'],


'sew_pond':			['q_info',
				'ufi',
				'symbol',
				'text_note'],


'canal_a':			['name',
				'q_info',
				'ufi',
				'symbol',
				'text_note'],

'rapid_a_l':			['q_info',
				'ufi',
				'symbol'],

'spring':			['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'tank_dam_p':			['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'bore':				['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'windpump':			['q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'waterpoint':			['waterpoint',
				'q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'trig_station':			['elevation',
				'code',
				'q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note',
				'order'],

'bench_mark':			['elevation',
				'code',
				'q_info',
				'ufi',
				'name',
				'symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'proh_a':			['name',
				'authority',
				'q_info',
				'ufi',
				'symbol'],

'proh_a_void':			['q_info',
				'ufi',
				'symbol'],

'proh_a_l':			['q_info',
				'ufi',
				'symbol',
				'feat_wid'],

'abor_res':			['name',
				'authority',
				'q_info',
				'ufi',
				'symbol'],

'forest_res':			['name',
				'authority',
				'q_info',
				'ufi',
				'symbol'],

'nat_res':			['name',
				'authority',
				'q_info',
				'ufi',
				'symbol'],

'water_res':			['name',
				'authority',
				'q_info',
				'ufi',
				'symbol'],

'res_a_void':			['q_info',
				'ufi',
				'symbol'],

'res_a_l':			['q_info',
				'ufi',
				'symbol',
				'feat_wid'],

'seismic_l':			['q_info',
				'ufi',
				'symbol'],

'internat_l':			['symbol',
				'text_note'],

'salt_ev_i_l':			['symbol'],

'sew_pond_i_l':			['symbol'],

'runway_c_l':			['symbol'],

'tropic_cap':			['symbol',
				'text_note'],

'pointer':			['symbol'],

'arrow_dest':			['symbol',
				'text_note'],

'transition_p':			['symbol',
				'feat_wid',
				'orientaton'],

'route_nat':			['symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'route_state':			['symbol',
				'feat_wid',
				'orientation',
				'text_note'],

'distance_ind':			['symbol',
				'feat_wid',
				'orientation'],

'pylon':			['symbol',
				'feat_wid',
				'orientation'],

'grid_map':			['symbol'],

'graticule':			['symbol'],

'map_area':			[],

'map_mask':			[]
}


